project/src/Entity/Project.php
<?php

namespace App\Entity;

use App\Repository\ProjectRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ProjectRepository::class)
 */
class Project
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255,unique=true)
     */
    private $title;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $Description;

    /**
     * @ORM\OneToMany(targetEntity=TimeLogs::class, mappedBy="project", orphanRemoval=true)
     */
    private $timeLogs;

    public function __construct()
    {
        $this->timeLogs = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(?string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    /**
     * @return Collection<int, TimeLogs>
     */
    public function getTimeLogs(): Collection
    {
        return $this->timeLogs;
    }

    public function addTimeLog(TimeLogs $timeLog): self
    {
        if (!$this->timeLogs->contains($timeLog)) {
            $this->timeLogs[] = $timeLog;
            $timeLog->setProject($this);
        }

        return $this;
    }

    public function removeTimeLog(TimeLogs $timeLog): self
    {
        if ($this->timeLogs->removeElement($timeLog)) {
            // set the owning side to null (unless already changed)
            if ($timeLog->getProject() === $this) {
                $timeLog->setProject(null);
            }
        }

        return $this;
    }
}

project/src/Controller/ProjectController.php
<?php

namespace App\Controller;

use App\Entity\Project;
use App\Entity\TimeLogs;
use App\Form\ProjectFormType;
use App\Repository\ProjectRepository;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\UX\Chartjs\Builder\ChartBuilderInterface;
use Symfony\UX\Chartjs\Model\Chart;

class ProjectController extends AbstractController
{


    /**
     * @Route("/", name="app_project_list")
     */
    public function list(ProjectRepository $projectRepository): Response
    {
        $projectList = $projectRepository->findAll();
        return $this->render('project/list.html.twig', [
            'projects' => $projectList,
        ]);
    }

    /**
     * @Route("/project", name="app_project_new")
     */
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(ProjectFormType::class);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $project = $form->getData();
            $entityManager->persist($project);
            $entityManager->flush();
            $this->addFlash('success', 'new project Added');
            return $this->redirectToRoute('app_project_list', [
            ]);
        }

        return $this->render('project/add.html.twig', [
            'controller_name' => 'ProjectController',
            'projectForm' => $form->createView()
        ]);
    }

    /**
     * @Route("/project/{id}/export", name="app_project_export")
     */
    public function export(Project $project, Request $request, EntityManagerInterface $entityManager): Response
    {
        $timeLogs = $project->getTimeLogs()->toArray();

        $data[] = [
            'project' => 'project_Title',
            'user' => 'user',
            'start At' => 'start_At',
            'Finish At' => 'Finish_At'
        ];
        $fp = fopen('php://temp', 'w');
        foreach ($timeLogs as $log) {
            $data[] = [
                'project' => $project->getTitle(),
                'user' => $log->getUser()->getUsername(),
                'start At' => $log->getStartAt()->format('d/m/Y'),
                'Finish At' => $log->getFinishAt()->format('d/m/Y')];
            foreach ($data as $fields) {
                fputcsv($fp, $fields);
            }
        }


        rewind($fp);
        $response = new Response(stream_get_contents($fp));
        fclose($fp);

        $response->headers->set('Content-Type', 'text/csv');
        $response->headers->set('Content-Disposition', 'attachment; filename="' . $project->getTitle() . '"_tasks_logs.csv');

        return $response;
    }


}

project/templates/project/_form.html.twig
{{ form_start(projectForm) }}

    {{ form_row(projectForm.title) }}
    {{ form_row(projectForm.Description) }}

<button type="submit" class="btn btn-primary">{{ button_text }}</button>
{{ form_end(projectForm) }}

project/templates/project/add.html.twig
{% extends 'base.html.twig' %}

{% block title %}create Project{% endblock %}

{% block body %}


<div class="container">
    {{ include('project/_form.html.twig', {
        button_text: 'Create!'
    }) }}
</div>
{% endblock %}

project/templates/project/list.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello HomeControlerController!{% endblock %}

{% block body %}


<div class="container">

    <h1>Project Lists</h1>
    <a href="{{ path('app_project_new') }}" class="btn btn-primary mb-5 float-right"> create new project</a>

    <table class="table">
        <thead>
        <tr>
            <th>Id</th>
            <th>Title</th>
            <th>Description</th>
            <th></th>
        </tr>

        </thead>
        <tbody>
        {% for project in projects %}
            <tr class="project-row" data-href="{{path('app_project_logs_list',{ id: project.id }) }}">
                <td>
                    {{ project.id }}
                </td>
                <td>
                    {{ project.title }}
                </td>
                <td>
                    {{ project.description }}
                </td>
                <td>
                    <a href="{{ path('app_project_export',{id:project.id}) }}" role="button" class="btn btn-info">Export Logs</a>
                </td>
            </tr>
        {% else %}
        {% endfor %}
        </tbody>

    </table>

</div>
{% endblock %}